field: 86f51cdf-0594-49d7-88cd-8cf8daddfd02 # Components
fieldLayouts:
  010096f1-9026-4c4a-adf0-c09ab46f4cc7:
    tabs:
      -
        elements:
          -
            fieldUid: 348dbe41-4699-43c4-aa30-5a9e894bb750 # Heading
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 5c506142-7e92-44a4-80d4-e3141c44deb1 # Abstract
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: Content
        sortOrder: 1
fields:
  5c506142-7e92-44a4-80d4-e3141c44deb1: # Abstract
    columnSuffix: null
    contentColumnType: text
    fieldGroup: null
    handle: abstract
    instructions: ''
    name: Abstract
    searchable: false
    settings:
      byteLimit: null
      charLimit: null
      code: ''
      columnType: null
      initialRows: '4'
      multiline: ''
      placeholder: null
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
  348dbe41-4699-43c4-aa30-5a9e894bb750: # Heading
    columnSuffix: null
    contentColumnType: text
    fieldGroup: null
    handle: heading
    instructions: ''
    name: Heading
    searchable: false
    settings:
      byteLimit: null
      charLimit: null
      code: ''
      columnType: null
      initialRows: '4'
      multiline: ''
      placeholder: null
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
handle: getInTouch
name: 'Get In Touch'
sortOrder: 2
