columnSuffix: null
contentColumnType: string
fieldGroup: d4e3d852-e984-4784-af34-69145961849c # Card
handle: cardThumbnail
instructions: ''
name: Thumbnail
searchable: false
settings:
  allowSelfRelations: false
  allowUploads: true
  allowedKinds:
    - image
  defaultUploadLocationSource: 'volume:c0a88e6f-7dc9-46ee-9c9f-cabe689dd5d5' # Components
  defaultUploadLocationSubpath: ''
  limit: '1'
  localizeRelations: false
  previewMode: full
  restrictFiles: '1'
  selectionLabel: ''
  showSiteMenu: true
  showUnpermittedFiles: false
  showUnpermittedVolumes: false
  singleUploadLocationSource: 'volume:c0a88e6f-7dc9-46ee-9c9f-cabe689dd5d5' # Components
  singleUploadLocationSubpath: ''
  source: null
  sources: '*'
  targetSiteId: null
  useSingleFolder: true
  validateRelatedElements: false
  viewMode: list
translationKeyFormat: null
translationMethod: site
type: craft\fields\Assets
